# Generated by Django 4.2.5 on 2023-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(blank=True, default='imagens/animal_fotos/NoImage.png', null=True, upload_to='imagens/animal_fotos/'),
        ),
    ]
